# === Required global config ===
ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc  = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

# === Trap configuration section ===
[traps]

# Your custom Time-Delay Operator Trap
[traps.time_delay_operator]
# Path to the trap ABI artifact
path = "out/TimeDelayOperatorTrap.sol/TimeDelayOperatorTrap.json"

# Your deployed responder contract address
response_contract = "0xb5a2814B916064b502C282A8BE60d1A9602C5E75"

# The responder function Drosera will call when the trap is triggered
response_function = "respond(address)"

# How many blocks worth of samples Drosera should inspect
block_sample_size = 5

# Blocks Drosera should wait before calling your responder again
cooldown_period_blocks = 0

# Whether this trap is private (recommended)
private_trap = true

# Address(es) allowed to trigger / interact with this trap
whitelist = ["0xd4d37413680cc2b8c2ea621993f6a2e226c48a6c"]
